### ISSUE TITLE
this is not work :)

### ISSUE THREAD

**Issue by Jonghyun-Yeom** [btk/binance-change-tracking#2]
hi, It looks like not work.
and your demo too.
please check it out :)
thank you.

**Comment by btk** [comment]
It does not work because the API is currently down for the system upgrade, and their current provider is getting ddosed;

https://twitter.com/cz_binance/status/961898898766770177

It should work after the issues are gone, tho I havent checked it, it mgiht be on my end.

**Comment by Jonghyun-Yeom** [comment]
thank you for your kindness answer :)
have a good day~
